Ability to enable detailed monitoring for EC2 instances
dask/dask-cloudprovider pull request #368
Opened 2022-08-02 20:58 UTC by pwerth

As title. See [here](See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-cloudwatch-new.html) for documentation on detailed vs. basic monitoring.

2022-08-03 08:47 UTC, jacobtomlinson requested changes
This looks great!

Could you change the default kwarg to `None` and load it from the `dask.config` for consistency with the other config options.

For example
https://github.com/dask/dask-cloudprovider/blob/3592253592b8aa8bf056542709c5cc2f2a3100de/dask_cloudprovider/aws/ec2.py#L473

2022-08-03 14:11 UTC, pwerth commented
> This looks great!
> 
> Could you change the default kwarg to `None` and load it from the `dask.config` for consistency with the other config options.
> 
> For example
> 
> https://github.com/dask/dask-cloudprovider/blob/3592253592b8aa8bf056542709c5cc2f2a3100de/dask_cloudprovider/aws/ec2.py#L473

Done! I also added the default to `cloudprovider.yaml`. 

FYI I have a [draft PR](https://github.com/dask/dask-cloudprovider/pull/357) to streamline a lot of the kwarg/config parsing in `ECSCluster`; something similar could probably be done in `EC2Cluster` as well. Not sure if you've seen that PR but do you think this is a worthwhile change? I can close the PR if you think it's not necessary.

2022-08-04 09:29 UTC, jacobtomlinson commented
> Done! I also added the default to cloudprovider.yaml.

Perfect thanks!

> Not sure if you've seen that PR but do you think this is a worthwhile change?

Apologies it had slipped past my radar. It looks great and I've commented over there.

2022-08-04 09:31 UTC, jacobtomlinson commented on dask_cloudprovider/aws/ec2.py
> +        enable_detailed_monitoring=False,
Should this also be `None` like the rest?

2022-08-04 09:31 UTC, jacobtomlinson commented on dask_cloudprovider/aws/ec2.py
> +        Default ``None``.
The docstring here should reflect the actual default, so from the config this would be ``False``.

2022-08-05 14:17 UTC, jacobtomlinson approved these changes
This is great thanks!

2022-08-05 14:17 UTC, merged